### ISSUE TITLE
SwiftUI Representable

### ISSUE THREAD

**Issue by marshallino16** [ProxymanApp/CodeMirror-Swift#3]
Hi, 

Any idea how to package this view into a Representable for SwiftUI?

Here's what I tried 

```swift
import Foundation
import SwiftUI


struct CodeView: NSViewRepresentable {
  
  func makeNSView(context: Context) -> CodeMirrorWebView {
    let codeMirrorView = CodeMirrorWebView()
    codeMirrorView.translatesAutoresizingMaskIntoConstraints = false
    return codeMirrorView
  }
  
  func updateNSView(_ codeMirrorView: CodeMirrorWebView, context: Context) {
    let url = Bundle.main.url(forResource: "data", withExtension: "json")!
    let content = try! String(contentsOf: url)
    codeMirrorView.setMimeType("application/json")
    codeMirrorView.setContent(content)
  }
}
```

**Comment by NghiaTranUIT** [comment]
Sorry but I haven't touched SwiftUI from the beginning day, so I don't know how to support you 😅 

If you could create a custom Representable, it should work with Codemirror since there are no special in the codebase 👍

**Comment by marshallino16** [comment]
Ok I did it but I had to : 

- replace the `CodeMirrorWebView` class by a representable handling the WKWebView

- wrap all WKWebView delegates into a `Coordinator`.

If you are ok, I'd like to package this into a SwiftUI code mirror package available via package manager and credit you for the work.

**Comment by NghiaTranUIT** [comment]
Feel free to do it. I appreciate all actions that help iOS/Mac developer 👍

**Comment by sonnyio** [comment]
Hey @marshallino16 would love to use the SwiftUI package. Will this be a new repo or a PR on this one? Could you share the link here if it's new?

**Comment by marshallino16** [comment]
Hi, it'll be a new package, crediting this one.
But I'll not release this week, probably the week after. I can send you my work though 😊

**Comment by sonnyio** [comment]
@marshallino16 Awesome, yeah I would really appreciate it! My email is on my profile.

**Comment by NghiaTranUIT** [comment]
Please let me know when it's public. I will add a link to your repo for anyone needs 👍

**Comment by marshallino16** [comment]
Here's the SwiftUI version, available via SPM @sonnyio 

https://github.com/Pictarine/CodeMirror-SwiftUI/

I'm closing this issue.
