### ISSUE TITLE
Error setContent

### ISSUE THREAD

**Issue by marshallino16** [ProxymanApp/CodeMirror-Swift#5]
Hi, 

When a String contains certain characters, `setContent()` doesn't work. 

To test : 

`"#Title\n``` test ```"`

or 

`"FROM spritsail/alpine-cmake\n\nWORKDIR /home\n\n# Global env\nRUN apk update \\\n    apk upgrade \\\n    apk add git tmux build-base curl bash\n\n\n# Dpkg\nRUN apk add dpkg pkgconfig\nRUN ls -a /var/lib/dpkg\nRUN touch /var/lib/dpkg/status\n\nRUN apk add --update --no-cache --repository http://dl-3.alpinelinux.org/alpine/edge/community --repository http://dl-3.alpinelinux.org/alpine/edge/main\n\nRUN apk add --update alpine-sdk\n\nRUN apk add glib libxml2 \\\n    libxslt fftw \\\n    gettext gtk+2.0 \\\n    python lcms \\\n    imagemagick-dev openexr \\\n    libwebp orc tiff poppler-glib librsvg libgsf\n\nRUN apk add --virtual vips-dependencies build-base \\\n    zlib-dev libxml2-dev glib-dev gobject-introspection-dev \\\n    libjpeg-turbo-dev libexif-dev lcms2-dev fftw-dev giflib-dev libpng-dev \\\n    libwebp-dev orc-dev tiff-dev poppler-dev librsvg-dev libgsf-dev openexr-dev \\\n    py-gobject3-dev flex bison\n\n\n# VIPS\nRUN \\\n    mkdir vips &&\\\n    pwd &&\\\n    ls -a &&\\\n    cd vips &&\\\n    wget -c https://github.com/jcupitt/libvips/releases/download/v8.5.9/vips-8.5.9.tar.gz &&\\\n    tar xzvf vips-8.5.9.tar.gz &&\\\n    cd /home/vips/vips-8.5.9 &&\\\n    dpkg --configure -a &&\\\n    ./configure &&\\\n    make &&\\\n    make install\n\n\n# PATH\nENV PATH \"${PATH}:/usr/local/lib/\"\n\n\n# FFMEG\nRUN apk add g++ ffmpeg ffmpeg-dev ffmpeg-libs\n\n\n# Tifig\nRUN \\\n    cd /home/ &&\\\n    git clone --recursive https://github.com/monostream/tifig.git &&\\\n    mkdir tifig/build && cd tifig/build &&\\\n    cmake .. &&\\\n    make\n\nRUN cp /home/tifig/build/tifig /usr/local/bin/tifig\n\n\n\n"`

Result : 

![Screen Shot 2020-08-26 at 3 33 22 PM](https://user-images.githubusercontent.com/1506323/91309922-84b67880-e7b1-11ea-8573-f92b676f0637.png)

**Comment by NghiaTranUIT** [comment]
It's the first drawback of using `String.raw()` since it doesn't work well if the content has some special characters

https://github.com/ProxymanApp/CodeMirror-Swift/blob/70a1de6caabe2352b37bee7fbc9bae3a5dafb09e/src/CodeMirrorWebView.swift#L102

In [Proxyman](https://github.com/ProxymanApp/Proxyman), I have to convert to Hex data, then passing to CodeMirror and convert back to the string.

**Comment by marshallino16** [comment]
Do you have any Snippet to share for that?

**Comment by NghiaTranUIT** [comment]
I've pushed the fix from Proxyman. Let check out the latest commit on the master https://github.com/ProxymanApp/CodeMirror-Swift/commit/87ba8d5ea65382c786ec599b6fa3544b5a94da2b

<img width="711" alt="Screen Shot 2020-08-26 at 20 47 27" src="https://user-images.githubusercontent.com/5878421/91311919-d8d75200-e7dd-11ea-815e-9058a24c91b2.png">
<img width="552" alt="Screen Shot 2020-08-26 at 20 47 33" src="https://user-images.githubusercontent.com/5878421/91311945-df65c980-e7dd-11ea-8ff0-b0137cae2c4c.png">

**Comment by marshallino16** [comment]
Wonderful, thank you 👍

**Comment by NghiaTranUIT** [comment]
Glad to help you 👍
